# Generated by Django 3.2.5 on 2021-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('question', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True, verbose_name='问题')),
                ('answer', models.CharField(max_length=500, verbose_name='答案')),
            ],
            options={
                'verbose_name': '问答对',
                'verbose_name_plural': '问答对',
                'db_table': 'qq_aa_y',
            },
        ),
    ]
